export const dataProjects = [
  {
    id:1,
    numer: "Proyect 3",
    name: "Reqres",
    image: "/reqres.png",
    description:"Proyecto reqres Practica , con Next js 14, NextAuth",
    url:"https://reqres-in-ruddy.vercel.app/",
    technologies:"NextJs 14, Typescript, NextAuth, Tailwind Css",
    github:"https://github.com/Orlandoc0107/reqres.in",
  },
  {
    id: 2,
    numer: "Proyect 2",
    name: "tp",
    image: "/Proyect2.png",
    description: "Nota: Breaches:Api-Rest . API rest , Django Presentado en el Curso de Fullstack Python en Argentina Programa",
    technologies: "Python// Django (==4.0.6), django-cors-headers, djangorestframework, djangorestframework-simplejwt, coreapi, setuptools",
    url: " ... ",
    github: "https://github.com/Orlandoc0107/tp/tree/Api-Rest",
  },
  {
    id: 3,
    numer: "Proyect 1",
    name: "EducaKids",
    image: "/EducaKids_version1.png",
    description: "Proyecto FrontEnd Presentado en el Curso de Fullstack Python en Codo a Codo",
    technologies: "HTML5 , CSS3 , JavaScript",
    url: "https://orlandoc0107.github.io/EducKids.github.io/",
    github: "https://github.com/Orlandoc0107/EducKids.github.io.git",
  },
];
